[package]
name = "rustronomy_sadf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustronomy_core = {path="../rustronomy_core"}
byteorder = "1"

[dev-dependencies]
rand = "0.8"