[package]
name = "oxyDF"
version = "0.1.0"
edition = "2021"

[lib]

[profile.release]
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"

[dev-dependencies]
rand = "0.8"